#!/bin/bash

# Apply patches
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/arcade/" < "${FILESDIR}/arcadebuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/aspnetcore/eng" < "${FILESDIR}/aspnetcorebuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/command-line-api/" < "${FILESDIR}/commandlineapbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/cecil/" < "${FILESDIR}/cecilbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/deployment-tools/" < "${FILESDIR}/deploymenttoolsbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/diagnostics/" < "${FILESDIR}/diagnosticsbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/repo-projects/" < "${FILESDIR}/directorybuildtargets.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/emsdk/" < "${FILESDIR}/emsdkbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/format/" < "${FILESDIR}/formatbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/fsharp/" < "${FILESDIR}/fsharpbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/installer/" < "${FILESDIR}/installerbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/installer/" < "${FILESDIR}/run-buildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/msbuild/" < "${FILESDIR}/msbuildbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/nuget-client/" < "${FILESDIR}/nugetclientbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/razor/" < "${FILESDIR}/razorbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/roslyn-analyzers/" < "${FILESDIR}/roslyn-analyzersbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/roslyn/" < "${FILESDIR}/roslynbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/runtime/" < "${FILESDIR}/runtimebuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/runtime/eng/" < "${FILESDIR}/sourcebuild.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/sdk/" < "${FILESDIR}/sdkbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/sourcelink/" < "${FILESDIR}/sourcelinkbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/source-build-externals/" < "${FILESDIR}/patches/srcbuildexternalsbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/source-build-externals/" < "${FILESDIR}/patches/srcbuildexternalsDirBuildProps.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/source-build-reference-packages" < "${FILESDIR}/patches/srcbuildrefpkgsbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/symreader/" < "${FILESDIR}/patches/symreaderbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/templating/" < "${FILESDIR}/patches/templatingbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/test-templates/" < "${FILESDIR}/patches/test-templatesbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/xdt/" < "${FILESDIR}/patches/xdtbuildsh.patch"
patch -d "${WORKDIR}/dotnet-sdk-8.0.0_rc1234194/src/xliff-tasks/" < "${FILESDIR}/patches/xliff-tasksbuildsh.patch"
